In [88]:

import numpy as np
#Создание мaтрицы 
n = 5
a = [[0] * n for _ in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j] = np.random.randint(1, 7)


In [89]:
def all_func(a, b, digit, eye_m):
    #v_v_mult
    size = len(a)
    m = [[0] * size for _ in range(size)]
    if len(a) != len(b) or len(a) != len(m):
        return 0
    for i in range(size):
        for j in range(size):
            m[i][j] = a[i] * b[j]
            m[i][j] = m[i][j] * digit
            eye_m[i][j] -= m[i][j]
    
    return eye_m
    
    

In [90]:
#умножение матриц
def matr_mult(first, second):
    length = len(first)
    result_matrix = [[0 for i in range(length)] for i in range(length)]
    for i in range(length):
        for j in range(length):
            for k in range(length):
                result_matrix[i][j] += first[i][k] * second[k][j]
    return result_matrix

In [91]:
def sign(x):
    return 1 if x >= 0 else -1 

In [94]:
def m_transform(a):
    size = len(a)
    for i in range(size - 2):
        norm = 0
        for j  in range(i+1, size, 1):
            norm += a[j][i] * a[j][i]
        norm = norm**0.5
        s = sign(a[i + 1][i]) * norm
        r = (2 * a[i + 1][i] * s + 2 * s * s)**0.5

        w = [0]*size

        w[i + 1] = (a[i + 1][i] + s) * (1 / r)
        for j in range(i+ 2, size, 1):
            w[j] = a[j][i] * (1 / r)
        
        eye = [[0] * size for _ in range(size)]
        for n in range(size):
            for m in range(size):
                if m == n:
                    eye[m][n] = 1
    
        h = all_func(w, w, 2, eye)
        a = matr_mult(h, a)
        a = matr_mult(a, h)
    return a

In [95]:
%%time
a = m_transform(a)

size = len(a)
for i in range(size):
    for j in range(size):
        a[i][j] = round(a[i][j], 2)
print(np.array(a))

[[ 6.    9.85  3.45 -2.74  0.75]
 [10.05 14.52  5.18 -1.32 -1.67]
 [ 0.    3.78  1.8   0.34  1.84]
 [ 0.    0.   -2.33 -3.02  1.  ]
 [ 0.    0.    0.    0.97 -0.3 ]]
CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 1.61 ms


In [96]:
from scipy.linalg import hessenberg

H, Q = hessenberg(a, calc_q=True)
H
size = len(H)
for i in range(size):
    for j in range(size):
        H[i][j] = round(H[i][j], 2)
print(np.array(H))

[[ 6.    9.85  3.45 -2.74  0.75]
 [10.05 14.52  5.18 -1.32 -1.67]
 [ 0.    3.78  1.8   0.34  1.84]
 [ 0.    0.   -2.33 -3.02  1.  ]
 [ 0.    0.    0.    0.97 -0.3 ]]
